name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      versions: '["truffleruby-head"]'
      min_version: 2.5

  build:
    needs: ruby-versions
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-13, windows-latest ]
        include:
          - ruby: mswin
            os: windows-latest
          - ruby: mingw
            os: windows-latest
        exclude:
          - ruby: head
            os: windows-latest
          - ruby: truffleruby-head
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - run: env | sort
    - run: |
        cc -xc -E - <<EOF
        #include <dlfcn.h>
        foo(RTLD_LAZY, RTLD_NOW, RTLD_LOCAL, RTLD_GLOBAL);
        EOF
    - name: Run test
      run: bundle exec rake compile test
      timeout-minutes: 5
      env:
        TESTOPTS: "--verbose"
        TRUFFLERUBYOPT: "--experimental-options --cexts-log-load"
