name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      versions: '["truffleruby-head"]'
      min_version: 2.5

  build:
    needs: ruby-versions
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ macos-latest ]
        include:
          - ruby: mswin
            os: windows-latest
          - ruby: mingw
            os: windows-latest
        exclude:
          - ruby: head
            os: windows-latest
          - ruby: truffleruby-head
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: time pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
    - run: time pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
    - run: time xcodebuild -version
    - run: time xcodebuild -version
